exclude = [".direnv/**/*", "target/**/*", "vendor/**/*"]

[formatting]
reorder_keys = false
inline_table_expand = false
compact_arrays = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "build-dependencies"]

[rule.formatting]
reorder_keys = true
