apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: data-1
  name: data-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
