apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: shared-1
  name: shared-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
