# Fork of the original crate: https://github.com/intel/SGXDataCenterAttestationPrimitives

[package]
name = "intel-tee-quote-verification-sys"
version = "0.2.0"
edition = "2021"
license = "BSD-3-Clause"

[build-dependencies]
bindgen.workspace = true
