[package]
name = "tdx-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
serde.workspace = true
teepot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
