[package]
name = "tee-key-preexec"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
secp256k1.workspace = true
teepot.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
