[package]
name = "tee-self-attestation-test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix-web.workspace = true
anyhow.workspace = true
base64.workspace = true
teepot.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
