[package]
name = "verify-era-proof-attestation"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
clap.workspace = true
enumset.workspace = true
hex.workspace = true
jsonrpsee-types = "0.25.1"
reqwest.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with = { workspace = true, features = ["hex"] }
serde_yaml = "0.9.33"
teepot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util = "0.7.14"
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
zksync_basic_types = "27.0.0-non-semver-compat"
zksync_types = "27.0.0-non-semver-compat"
zksync_web3_decl = "27.0.0-non-semver-compat"
