name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: enarx/spdx@c3e8116ed31c31b3c2e58a26ba5cac407510ca37
        with:
          licenses: |-
            Apache-2.0
            BSD-3-Clause
            MIT

  taplo:
    name: taplo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: cachix/install-nix-action@v30
      - run: nix run nixpkgs#taplo -- fmt --check
