name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: enarx/spdx@b5bfdd4410071bf058c8333d0e70020001524b6b
        with:
          licenses: |-
            Apache-2.0
            BSD-3-Clause
            MIT

  taplo:
    name: taplo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@v30
      - run: nix run nixpkgs#taplo -- fmt --check
